export default [
  {
    id: 'internet-censorship-in-kazakhstan-part-1',
    title: 'Internet Censorship In Kazakhstan, Part 1',
    description: 'How Do They Do It? Content Blocking, Kazakhstan Edition.',
    tags: ['en', 'networks', 'privacy'],
    createdAt: '2020-07-01',
    public: true,
  },
  {
    id: 'quit-facebook-ecosystem',
    title: '#quitFacebookEcosystem',
    description: 'Why leave social media backed by Big Brother - Facebook?',
    tags: ['en', 'social-media', 'privacy'],
    createdAt: '2020-06-25',
    public: true,
  },
  {
    id: 'ruined-expectations-from-unist',
    title: 'Ruined expectations from UNIST',
    description:
      'Rants about what I like and (mostly) dislike about my university.',
    tags: ['en', 'rants', 'university'],
    createdAt: '2020-05-26',
    public: true,
  },
  {
    id: 'test-code',
    title: 'Testing Code In MDX',
    description: 'Check if code wrapper components work.',
    tags: ['test', 'code', 'en'],
    createdAt: '2020-04-09',
    public: false,
  },
  {
    id: 'uiso-2019',
    title: 'UISO 2019',
    description: 'Essay on leadership.',
    tags: ['unist', 'personal', 'leadership', 'en'],
    createdAt: '2018-11-14',
    public: true,
  },
  {
    id: 'sleep-less-feel-better',
    title: 'Sleep Less, Feel Better',
    description: 'Guide to a healthy sleep.',
    tags: ['unist', 'health', 'en'],
    createdAt: '2018-01-19',
    public: true,
  },
  {
    id: 'no-more-sbornik',
    title: 'No More "Sbornik"',
    description: 'Republican Olympiad in Pavlodar.',
    tags: ['personal', 'olympiads', 'photos', 'en'],
    createdAt: '2017-03-28',
    public: true,
  },
  {
    id: 'getting-out-of-the-comfort-zone',
    title: 'Getting Out Of The Comfort Zone',
    description: 'My thoughts on performing well at various exams.',
    tags: ['personal', 'olympiads', 'exams', 'en'],
    createdAt: '2016-12-24',
    public: true,
  },
  {
    id: 'i-am-back-again',
    title: "I'm Back... (again)",
    description: 'My Personal View on Augmented Reality.',
    tags: ['personal', 'thoughts', 'ru'],
    createdAt: '2016-09-12',
    public: true,
  },
  {
    id: 'trying-to-do-my-best',
    title: 'Trying To Do My Best',
    description: 'It’s been a long time since I last wrote here (2 months).',
    tags: ['personal', 'olympiads', 'en'],
    createdAt: '2016-03-09',
    public: true,
  },
];
