export default [
  {
    id: 'new-post',
    title: 'New Post Title',
    description: 'New Post Description',
    tags: ['en'],
    createdAt: '2020-05-19',
    public: false,
  },
  {
    id: 'test-code',
    title: 'Testing Code In MDX',
    description: 'Check if code wrapper components work.',
    tags: ['test', 'code', 'en'],
    createdAt: '2020-04-09',
    public: false,
  },
  {
    id: 'uiso-2019',
    title: 'UISO 2019',
    description: 'Essay on leadership.',
    tags: ['unist', 'personal', 'leadership', 'en'],
    createdAt: '2018-11-14',
    public: true,
  },
  {
    id: 'sleep-less-feel-better',
    title: 'Sleep Less, Feel Better',
    description: 'Guide to a healthy sleep.',
    tags: ['unist', 'health', 'en'],
    createdAt: '2018-01-19',
    public: true,
  },
  {
    id: 'no-more-sbornik',
    title: 'No More "Sbornik"',
    description: 'Republican Olympiad in Pavlodar.',
    tags: ['personal', 'olympiads', 'photos', 'en'],
    createdAt: '2017-03-28',
    public: true,
  },
  {
    id: 'getting-out-of-the-comfort-zone',
    title: 'Getting Out Of The Comfort Zone',
    description: 'My thoughts on performing well at various exams.',
    tags: ['personal', 'olympiads', 'exams', 'en'],
    createdAt: '2016-12-24',
    public: true,
  },
  {
    id: 'i-am-back-again',
    title: "I'm Back... (again)",
    description: 'My Personal View on Augmented Reality.',
    tags: ['personal', 'thoughts', 'ru'],
    createdAt: '2016-09-12',
    public: true,
  },
  {
    id: 'trying-to-do-my-best',
    title: 'Trying To Do My Best',
    description: 'It’s been a long time since I last wrote here (2 months).',
    tags: ['personal', 'olympiads', 'en'],
    createdAt: '2016-03-09',
    public: true,
  },
];
